//  TRANSACTION ACTIONS
export const ADD_RECURRING_TRANSACTION = 'ADD_RECURRING_TRANSACTION';
export const DELETE_RECURRING_TRANSACTION = 'DELETE_RECURRING_TRANSACTION';
export const LOAD_RECURRING_TRANSACTIONS = 'LOAD_RECURRING_TRANSACTIONS';
export const LOAD_TRANSACTIONS = 'LOAD_TRANSACTIONS';
export const SET_DATE = 'SET_DATE';

// STATISTIC ACTIONS
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const SAVE_TRANSACTIONS = 'SAVE_TRANSACTIONS';
export const SAVE_ALL_TRANSACTIONS = 'SAVE_ALL_TRANSACTIONS';
export const CALCULATE_STATISTICS = 'CALCULATE_STATISTICS';

// USER ACTIONS
export const LOAD_USER = 'LOAD_USER';
export const LOGIN = 'LOGIN';

// TRANSACTION/USER ACTIONS
export const LOGOUT = 'LOGOUT';

// PAGE ACTIONS
export const SET_MESSAGE = 'SET_MESSAGE';