//  TRANSACTION ACTIONS
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const LOAD_TRANSACTIONS = 'LOAD_TRANSACTIONS';
export const SAVE_TRANSACTIONS = 'SAVE_TRANSACTIONS';
export const SET_DATE = 'SET_DATE';

// USER ACTIONS
export const LOAD_USER = 'LOAD_USER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';